version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Ignore specific dependencies
    ignore:
      - dependency-name: "postcss"
      - dependency-name: "@radix-ui/*"
        versions: ["*"]
      - dependency-name: "tailwindcss"
        versions: ["*"]
      - dependency-name: "autoprefixer"
        versions: ["*"]
    
    # Optional: Configure how many PRs to open at once
    open-pull-requests-limit: 2
        
    # Optional: Add labels to PRs
    labels:
      - "dependencies"
      - "automated"